name: drone-dl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - pillow>=9.0.0
  - tqdm>=4.64.0
  - requests>=2.28.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - black>=23.0.0
  - isort>=5.12.0
  - pip
  # Linux dependencies
  - libglib
  - libopencv
  - libpng
  - libtiff
  - libjpeg-turbo
  - cairo
  - gdk-pixbuf
  - pango
  - freetype
  - pip:
      - streamlit>=1.28.0
      - torch>=1.12.0
      - torchvision>=0.13.0
      - albumentations>=1.2.0
      - opencv-python>=4.5.0
      - rasterio>=1.3.0
      - torchsummary>=1.5.1
      - mlflow>=2.10.0
