[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["app", "data_setup", "lightning_unet", "unet_model", "test_model", "streamlit_app"]
known_third_party = ["torch", "torchvision", "numpy", "scikit-learn", "rasterio", "albumentations", "Pillow", "matplotlib", "tqdm", "torchsummary", "cv2", "flask", "streamlit"] 
